/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jjmd_ndkdemo_JniUtils */

#ifndef _Included_cn_jjmd_ndkdemo_JniUtils
#define _Included_cn_jjmd_ndkdemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jjmd_ndkdemo_JniUtils
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_jjmd_ndkdemo_JniUtils_getStringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
